name: "Run Runtime Action Iac"
description: "Runs Runtime Action Iac with parameters"
inputs:
  FEATURES_LEVEL_LOG:
    description: "Log Level"
    required: true
  CLIENT_ID:
    description: "CLIENT ID"
    required: true
  CLIENT_KEY:
    description: "CLIENT KEY"
    required: true
  CLIENT_REALM:
    description: "CLIENT REALM"
    required: true
  AWS_ACCESS_KEY_ID:
    description: "AWS ACCESS KEY ID from console"
    required: false
  AWS_SECRET_ACCESS_KEY:
    description: "AWS SECRET ACCESS KEY from console"
    required: false
  AWS_SESSION_TOKEN:
    description: "AWS SESSION TOKEN from console"
    required: false
  AWS_REGION:
    description: "AWS REGION"
    required: true
  AWS_ROLE_ARN:
    description: "AWS ROLE ARN"
    required: false
  RUN_TASK_ID:
    description: "Runtime Run Task Id"
    required: true
  BASE_PATH_OUTPUT:
    description: "Base Path Output"
    required: false
  CONTAINER_URL:
    description: "IAC Container url"
    default: stackspot/runtime-job-iac

runs:
  using: "composite"
  steps:
    - name: Check Runner
      run: echo 🤖 OS runner is $(uname)
      shell: bash

    - name: Clear AWS ENV VAR if exists
      if: ${{ inputs.AWS_ROLE_ARN != 0 }}
      run: |
        export BACKUP_AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        export BACKUP_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        export BACKUP_AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
        unset AWS_ACCESS_KEY_ID
        unset AWS_SECRET_ACCESS_KEY
        unset AWS_SESSION_TOKEN
      shell: bash

    - name: Configure aws credentials
      id: aws-cred
      if: ${{ inputs.AWS_ROLE_ARN != 0 }}
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ inputs.AWS_ROLE_ARN }}
        aws-region: ${{ inputs.AWS_REGION }}
        output-credentials: true
      
    - name: Run Runtime Action Iac
      if: ${{ inputs.AWS_ROLE_ARN == 0 }}
      run: |
        docker run --rm \
        -e FEATURES_LEVEL_LOG=${{ inputs.FEATURES_LEVEL_LOG }} \
        -e AUTHENTICATE_CLIENT_ID=${{ inputs.CLIENT_ID }} \
        -e AUTHENTICATE_CLIENT_SECRET=${{ inputs.CLIENT_KEY }} \
        -e AUTHENTICATE_CLIENT_REALMS=${{ inputs.CLIENT_REALM }} \
        -e AUTHENTICATE_URL="https://idm.stackspot.com" \
        -e FEATURES_API_MANAGER="https://runtime-manager.v1.stackspot.com" \
        -e AWS_ACCESS_KEY_ID=${{ inputs.AWS_ACCESS_KEY_ID }} \
        -e AWS_SECRET_ACCESS_KEY=${{ inputs.AWS_SECRET_ACCESS_KEY }} \
        -e AWS_SESSION_TOKEN=${{ inputs.AWS_SESSION_TOKEN }} \
        -e AWS_REGION=${{ inputs.AWS_REGION }} \
        --entrypoint=/app/stackspot-runtime-job-iac \
        ${{ inputs.CONTAINER_URL }}:2.11.0 start --run-task-id="${{ inputs.RUN_TASK_ID }}" --base-path-output="${{ inputs.BASE_PATH_OUTPUT }}"
      shell: bash

    - name: Run Runtime Action Iac
      if: ${{ inputs.AWS_ROLE_ARN != 0 }}
      run: |
        docker run --rm \
        -e FEATURES_LEVEL_LOG=${{ inputs.FEATURES_LEVEL_LOG }} \
        -e AUTHENTICATE_CLIENT_ID=${{ inputs.CLIENT_ID }} \
        -e AUTHENTICATE_CLIENT_SECRET=${{ inputs.CLIENT_KEY }} \
        -e AUTHENTICATE_CLIENT_REALMS=${{ inputs.CLIENT_REALM }} \
        -e AUTHENTICATE_URL="https://idm.stackspot.com" \
        -e FEATURES_API_MANAGER="https://runtime-manager.v1.stackspot.com" \
        -e AWS_ACCESS_KEY_ID=${{ steps.aws-cred.outputs.aws-access-key-id }} \
        -e AWS_SECRET_ACCESS_KEY=${{ steps.aws-cred.outputs.aws-secret-access-key }} \
        -e AWS_SESSION_TOKEN=${{ steps.aws-cred.outputs.aws-session-token }} \
        -e AWS_REGION=${{ inputs.AWS_REGION }} \
        --entrypoint=/app/stackspot-runtime-job-iac \
        ${{ inputs.CONTAINER_URL }}:2.11.0 start --run-task-id="${{ inputs.RUN_TASK_ID }}" --base-path-output="${{ inputs.BASE_PATH_OUTPUT }}"
      shell: bash

    - name: Reset AWS ENV VAR if exists
      if: ${{ inputs.AWS_ROLE_ARN != 0 }}
      run: |
        export AWS_ACCESS_KEY_ID=$BACKUP_AWS_ACCESS_KEY_ID
        export AWS_SECRET_ACCESS_KEY=$BACKUP_AWS_SECRET_ACCESS_KEY
        export AWS_SESSION_TOKEN=$BACKUP_AWS_SESSION_TOKEN
        unset BACKUP_AWS_ACCESS_KEY_ID
        unset BACKUP_AWS_SECRET_ACCESS_KEY
        unset BACKUP_AWS_SESSION_TOKEN
      shell: bash

branding:
    icon: 'terminal'
    color: 'orange'
